(ns secret-santa-app.email.email)
(import org.apache.commons.mail.DefaultAuthenticator)
(import org.apache.commons.mail.EmailException)
(import org.apache.commons.mail.SimpleEmail)

(def email (new SimpleEmail))
(def from "")
(def to "")
(def port 587)
(def host "smtp.gmail.com")
(def pw "")
(. email setDebug true)
(. email setAuthenticator (new DefaultAuthenticator from pw))
(. email setMsg "this came from the heroku")
(. email setFrom from)
(. email addTo "timothy.d.butterworth@gmail.com" "John Doe")
(. email setSubject "hi from clojure web on Heroku")
(. email setSmtpPort port)
(. email setHostName host)
(. email setTLS true)
(defn send-email [] (. email send))
